# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Keycloak installation tasks
  when: keycloak_enabled | bool
  tags:
    - setup-all
    - setup-keycloak
    - install-all
    - install-keycloak
  block:
    - name: Validate Keycloak configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Keycloak
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Keycloak uninstallation tasks
  when: not keycloak_enabled | bool
  tags:
    - setup-all
    - setup-keycloak
  block:
    - name: Uninstall Keycloak
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
