# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform Keycloak installation tasks
  block:
    - name: Validate Keycloak configuration
      when: keycloak_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install Keycloak
      when: keycloak_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-keycloak
    - install-all
    - install-keycloak

- name: Perform Keycloak uninstallation tasks
  block:
    - name: Uninstall Keycloak
      when: not keycloak_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-keycloak
